server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://a28863b2350a2491e9787ed09b8f4915-2051992734.us-east-1.elb.amazonaws.com/api/;
        proxy_set_header Host a28863b2350a2491e9787ed09b8f4915-2051992734.us-east-1.elb.amazonaws.com;
        proxy_set_header X-Real-IP $remote_addr;
    }
}